### ISSUE TITLE
make available through pip

### ISSUE THREAD

**Issue by TonyBagnall** [sktime/sktime-neuro#7]
to allow pip install.

**Comment by SveaMeyer13** [comment]
Hi @TonyBagnall. You can already pip install this using: 

`pip install -e .`

If you'd want to make it available through PyPI, this repository would need to be public.

**Comment by TonyBagnall** [comment]
Ah ok, let's do that when it's public then

**Comment by juliencarponcy** [comment]
Hi, it is apparently public now.

If you want to make it available by PyPi or conda that would be nice!

This project is an excellent initiative! Looking forward to use it

**Comment by TonyBagnall** [comment]
hi, thanks for that, I hope to be able to give this more attention this year, and we have some MSc students working on it, so watch this space :)
